/* Generated by AN DISI Unibo */ 
package it.unibo.ctxcss_test_deposit
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	//System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "localhost", this, "test_deposit_sprint1.pl", "sysRules.pl", "ctxcss_test_deposit"
	)
}

