/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
class Transporttrolley ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var TruckTicket : Int = 0	
				return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("TRANSPORT TROLLEY STARTING")
						CommUtils.outgreen("TRANSP sto provando a mandare una richiesta di engage al BASIC ROBOT")
						request("engage", "engage(transporttrolley,250)" ,"basicrobot" )  
						forward("updateled", "updateled(HOME)" ,"warningdevice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="waiting",cond=whenReply("engagedone"))
					transition(edgeName="t09",targetState="errorengage",cond=whenReply("engagerefused"))
				}	 
				state("errorengage") { //this:State
					action { //it:State
						CommUtils.outred("engage del basicrobot fallito")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outgreen("TRANSP: waiting for requests...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="movetoindoor",cond=whenRequest("loaddone"))
				}	 
				state("movetoindoor") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loaddone(TruckTicket)"), Term.createTerm("loaddone(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 TruckTicket = payloadArg(0).toInt()  
						}
						CommUtils.outgreen("il driver con ticket $TruckTicket è pronto all'indoor, avvio dell'operazione di scarico dal camion...")
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						forward("updateled", "updateled(MOVING)" ,"warningdevice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="handlecharge",cond=whenReply("moverobotdone"))
					transition(edgeName="t012",targetState="errordeposit",cond=whenReply("moverobotfailed"))
					transition(edgeName="t013",targetState="handlestop",cond=whenDispatch("stop"))
				}	 
				state("handlestop") { //this:State
					action { //it:State
						CommUtils.outgreen("stop del robot, l'alarmDevice ha rilevato una distanza inferiore a DLIMIT")
						forward("updateled", "updateled(STOPPED)" ,"warningdevice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("errordeposit") { //this:State
					action { //it:State
						CommUtils.outred("operazione di deposito fallita, si procede con le prossime richieste...")
						forward("depositfailed", "depositfailed($TruckTicket)" ,"coldroommanager" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("handlecharge") { //this:State
					action { //it:State
						CommUtils.outgreen("il robot è arrivato all'indoor, inizio scarico della merce dal camion...")
						delay(3000) 
						answer("loaddone", "goaway", "goaway(_)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="movetoport", cond=doswitch() )
				}	 
				state("movetoport") { //this:State
					action { //it:State
						CommUtils.outgreen("il camion è stato scaricato, il robot si dirige verso la porta della cold room...")
						request("moverobot", "moverobot(4,3)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="handledeposit",cond=whenReply("moverobotdone"))
					transition(edgeName="t015",targetState="errordeposit",cond=whenReply("moverobotfailed"))
				}	 
				state("handledeposit") { //this:State
					action { //it:State
						CommUtils.outgreen("il robot è arrivato davanti alla cold room, inizia la fase di deposito...")
						delay(3000) 
						forward("depositdone", "depositdone($TruckTicket)" ,"coldroommanager" ) 
						CommUtils.outgreen("deposito effettuato con successo")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="gohome", cond=doswitch() )
				}	 
				state("gohome") { //this:State
					action { //it:State
						CommUtils.outgreen("ritorno del robot alla posizione home in corso...")
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
