/* Generated by AN DISI Unibo */ 
package it.unibo.ctxaccessgui
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	//System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "10.201.7.226", this, "coldstorageservice.pl", "sysRules.pl", "ctxaccessgui"
	)
}

