/* Generated by AN DISI Unibo */ 
package it.unibo.ctxraspberrypi
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	//System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "192.168.59.244", this, "coldstorageservice.pl", "sysRules.pl", "ctxraspberrypi"
	)
}

